### ISSUE TITLE
No cargan los graficos

### ISSUE THREAD

**Issue by Rayman18x** [GabrielVelasco/BET-Attack-Momentum#1]
Hola amigo, descubrí tu api hace una semana y la verdad que esta súper bien, la utilizo mucho y da resultados.
Lo único que lleva un par de días que no carga los gráficos.

**Comment by GabrielVelasco** [comment]
Olá amigo, tudo bem? 
O SofaScore trocou a url do iframe dos gráficos e a end-point da API para pegar a lista de jogos ao vivo. Arrumei o código e agora parece estar funcionando :)

Fico feliz que a api está sendo util para você :) obrigado por me ajudar :) Este é um projeto público e qualquer um é bem vindo.

Gracias.

**Comment by Rayman18x** [comment]
Muchas gracias amigo
Saludos desde Madrid
