### ISSUE TITLE
Saudações, sugestão 

### ISSUE THREAD

**Issue by edirosky** [GabrielVelasco/BET-Attack-Momentum#2]
Podias tentar fazer outro, mas com dados do sokkerpro.
o momento de ataque é mais completo e interessante no sokkerpro.com.
continuação de bons trabalhos.

**Comment by edirosky** [comment]
![Screenshot_2024-06-11-22-04-49-656_com kiwibrowser browser](https://github.com/GabrielVelasco/BET-Attack-Momentum/assets/36491022/c333d482-bd7a-432d-b6ed-8abbb71d4a05)

Este é um projecto meu, feito no python, alojado no Google Colab. 
Só que demora muito a carregar para o github.

**Comment by GabrielVelasco** [comment]
Saudações!

Vi que a API do sokkerPRO retorna alguns dados interessantes como ataques por minutos, mas depois de assistir um pouco da partida entre Atletico Mineiro vs Bragantino, eu achei o gráfico do SofaScore mais preciso e simples (conta melhor a história do jogo, mas é minha opinião).

A API do SofaScore retorna vários outros dados que não são mostrados no site, como xG, escanteios, chutes, grandes chances e etc. Eu tenho planos de refazer este site usando React, vai ficar mais fácil/rápido de desenvolver e mostrar mais dados para cada partida, porém no momento eu não estou com muito tempo livre por causa da faculdade e trabalho, mas quero fazer assim que possível.

Acho que a vantagem de usar o gráfico do SofaScore é que ele ja vem "pronto", já o do sokkerPRO tem que montar o gráfico com vc fez no seu projeto (ficou legal :D), e o do sofascore atualiza de minuto em minuto.

Tem muito a melhorar neste projeto, pretendo dedicar mais tempo a ele, e usando React vai ser muito mais fácil de desenvolver e acredito terá um desempenho descente.

Sinta-se livre para copiar este código e fazer melhorias... Obrigado pela contribuição :)
